import = [
	"~/.config/alacritty/themes/carbonfox.toml"
]
live_config_reload = true



[window]
decorations = "None"
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 11
offset = { x = 0, y = -1 }

[mouse]
hide_when_typing = true
